### ISSUE TITLE
Blank recipe

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-react#1]
![Screenshot (103)](https://github.com/MuhammadSonySetiawan/pijar-food-react/assets/49361887/99ebdfe1-adbb-4b26-b210-942516929ec6)
![Screenshot (104)](https://github.com/MuhammadSonySetiawan/pijar-food-react/assets/49361887/3fa57d53-c52c-4eda-9bf6-4a6149c0934f)

**Comment by MuhammadSonySetiawan** [comment]
fixing empty bug content
![Home](https://github.com/MuhammadSonySetiawan/pijar-food-react/assets/132990489/41ca7fd8-6ccd-4e97-8071-c4631d4f9cd8)
